### ISSUE TITLE
System.IndexOutOfRangeException: Index {0} is out of range of '{1}' Length.

### ISSUE THREAD

**Issue by lil-mason-mcgough** [Unity-Technologies/SynthDet#11] opened 2020-06-17 23:36 UTC
I am trying to run the SynthDet simulation in the Unity Editor, but it fails with this error before finishing after about 3775 frames. 

**System**
Ubuntu 18.04

**Console logs / stack trace**
```
System.IndexOutOfRangeException: Index {0} is out of range of '{1}' Length.
Thrown from job: ForegroundObjectPlacer.ComputePlacementsJob
This Exception was thrown from a job compiled with Burst, which has limited exception support. Turn off burst (Jobs -> Burst -> Enable Compilation) to inspect full exceptions & stacktraces.

UnityEngine.Debug:Log(Object)
EndSimulationSystem:OnUpdate() (at Assets/Scripts/EndSimulationSystem.cs:26)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystem.cs:108)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystemGroup.cs:134)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystemGroup.cs:114)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystem.cs:108)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ScriptBehaviourUpdateOrder.cs:152)

DC[V]: Application quit
UnityEngine.Debug:Log(Object)
Unity.Simulation.Log:Write(Level, String, Boolean) (at Library/PackageCache/com.unity.simulation.core@0.0.10-preview.11/Runtime/Log.cs:80)
Unity.Simulation.Log:V(String, Boolean) (at Library/PackageCache/com.unity.simulation.core@0.0.10-preview.11/Runtime/Log.cs:135)
Unity.Simulation.Manager:Update(Single) (at Library/PackageCache/com.unity.simulation.core@0.0.10-preview.11/Runtime/Manager.cs:401)
Unity.Simulation.Manager:Shutdown() (at Library/PackageCache/com.unity.simulation.core@0.0.10-preview.11/Runtime/Manager.cs:341)
Unity.Simulation.<>c:<.cctor>b__0_0(PlayModeStateChange) (at Library/PackageCache/com.unity.simulation.core@0.0.10-preview.11/Editor/ExitPlaymode.cs:17)
UnityEditor.EditorApplication:ExitPlaymode()
EndSimulationSystem:OnUpdate() (at Assets/Scripts/EndSimulationSystem.cs:28)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystem.cs:108)
Unity.Entities.ComponentSystemGroup:UpdateAllSystems() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystemGroup.cs:134)
Unity.Entities.ComponentSystemGroup:OnUpdate() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystemGroup.cs:114)
Unity.Entities.ComponentSystem:Update() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ComponentSystem.cs:108)
Unity.Entities.DummyDelegateWrapper:TriggerUpdate() (at Library/PackageCache/com.unity.entities@0.8.0-preview.8/Unity.Entities/ScriptBehaviourUpdateOrder.cs:152)
```

**Comment by Wesley201** [comment] 2020-06-24 20:30
Thank you for reporting the issue to us, we currently have a Dev looking at the issue and hopefully have a fix soon.

**Comment by nupur-yadav** [comment] 2020-06-29 20:21
@lil-mason-mcgough  the issue is now fixed. Thanks for reporting it.

**Closed by nupur-yadav** 2020-06-29 20:21 UTC
